//This lowkey clean
[assembly: System.Reflection.AssemblyTitle("Soundify")]
[assembly: System.Reflection.AssemblyDescription(Info.Description)]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany($"{Info.Author} (www.scrim.cc)")]
[assembly: System.Reflection.AssemblyProduct("Soundify")]
[assembly: System.Reflection.AssemblyCopyright($"Copyright {Info.Author} ©  2024")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid(Info.GUID)]
[assembly: System.Reflection.AssemblyVersion(Info.AppVersion)]
[assembly: System.Reflection.AssemblyFileVersion(Info.AppVersion)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]